# ============================================================================
# Adjoint Fluid Control
# ============================================================================
add_library(physica-fluids-gas-adjoint-control)
target_sources(
        physica-fluids-gas-adjoint-control
        PRIVATE
        control.cpp
        control.cu
        control_kernels.h
        derivative-check.cpp
        device.h
        device.cuh
        diffusion.cu
        domain.cpp
        domain.cu
        domain_kernels.h
        evaluation.cpp
        forces.cu
        interop.h
        lbfgsb.cpp
        mass.cu
        objective.cpp
        objective.cu
        objective_kernels.h
        projection.cu
        sampling.cuh
        solver.cpp
        solver_kernels.h
        transport.cu
        PUBLIC
        FILE_SET cxx_modules TYPE CXX_MODULES FILES
        control.ixx
        derivative-check.ixx
        domain.ixx
        evaluation.ixx
        adjoint-control.ixx
        lbfgsb.ixx
        objective.ixx
        solver.ixx
)
target_include_directories(
        physica-fluids-gas-adjoint-control
        PUBLIC
        "${PHYSICA_CLION_CUDA_INCLUDE_DIRECTORY}"
)
target_link_libraries(
        physica-fluids-gas-adjoint-control
        PUBLIC
        CCCL::libcudacxx
        CUDA::toolkit
)
