# ============================================================================
# Adjoint Fluid Control
# ============================================================================
add_library(physica-fluids-gas-adjoint-control)
target_sources(
        physica-fluids-gas-adjoint-control
        PRIVATE
        control/control.cpp
        control/control.cu
        control/kernels.h
        domain/device.h
        domain/device.cuh
        domain/domain.cpp
        domain/domain.cu
        domain/interop.h
        domain/kernels.h
        evaluation/derivative-check.cpp
        evaluation/evaluation.cpp
        objective/kernels.h
        objective/objective.cpp
        objective/objective.cu
        optimization/lbfgsb.cpp
        solver/diffusion.cu
        solver/forces.cu
        solver/kernels.h
        solver/mass.cu
        solver/projection.cu
        solver/sampling.cuh
        solver/solver.cpp
        solver/transport.cu
        PUBLIC
        FILE_SET cxx_modules TYPE CXX_MODULES FILES
        adjoint-control.ixx
        control/control.ixx
        domain/domain.ixx
        evaluation/derivative-check.ixx
        evaluation/evaluation.ixx
        objective/objective.ixx
        optimization/lbfgsb.ixx
        solver/solver.ixx
)
target_include_directories(
        physica-fluids-gas-adjoint-control
        PUBLIC
        "${PHYSICA_CLION_CUDA_INCLUDE_DIRECTORY}"
)
target_link_libraries(
        physica-fluids-gas-adjoint-control
        PUBLIC
        CCCL::libcudacxx
        CUDA::toolkit
)
