#ifndef PHYSICA_FLUIDS_LIQUID_SOLVERS_PBF_KERNELS_H
#define PHYSICA_FLUIDS_LIQUID_SOLVERS_PBF_KERNELS_H

#include <physica/fluids/liquid/device.cuh>
#include <cstdint>
#include <physica/cuda_stream.h>

namespace physica::fluids::liquid::pbf::kernels {

    void launch_predict_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float gravity_x, float gravity_y, float gravity_z, field::VectorView<const float> positions, field::VectorView<const float> velocities, field::VectorView<const float> controls, field::VectorView<float> predicted_positions);
    void launch_predict_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, field::VectorView<const float> position_tangent, field::VectorView<const float> velocity_tangent, field::VectorView<const float> control_tangent, field::VectorView<float> predicted_position_tangent);
    void launch_predict_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, field::VectorView<const double> predicted_position_adjoint, field::VectorView<double> position_adjoint, field::VectorView<double> velocity_adjoint, field::VectorView<double> control_adjoint);

    void launch_lambda_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, device::ParticleParameterView particles, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, const float* relaxation, field::VectorView<float> gradient_sums, float* denominators, float* lambdas);
    void launch_lambda_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> position_tangent, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, const float* density_tangent, const float* relaxation, const float* relaxation_tangent, field::VectorView<float> gradient_sum_tangent, float* denominator_tangent, float* lambda_tangent);
    void launch_lambda_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, device::ParticleParameterView particles, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, field::VectorView<const float> gradient_sums, const float* denominators, const double* lambda_adjoint, field::VectorView<double> position_adjoint, double* density_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* relaxation_adjoint);

    void launch_correction_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, device::ParticleParameterView particles, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* lambdas, const float* artificial_pressure_strength, const float* artificial_pressure_exponent, const float* artificial_pressure_radius, field::VectorView<float> corrections);
    void launch_correction_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> position_tangent, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* lambdas, const float* lambda_tangent, const float* artificial_pressure_strength, const float* artificial_pressure_strength_tangent, const float* artificial_pressure_exponent, const float* artificial_pressure_exponent_tangent, const float* artificial_pressure_radius, const float* artificial_pressure_radius_tangent, field::VectorView<float> correction_tangent);
    void launch_correction_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, device::ParticleParameterView particles, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* lambdas, const float* artificial_pressure_strength, const float* artificial_pressure_exponent, const float* artificial_pressure_radius, field::VectorView<const double> correction_adjoint, field::VectorView<double> position_adjoint, double* lambda_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* artificial_pressure_strength_adjoint, double* artificial_pressure_exponent_adjoint, double* artificial_pressure_radius_adjoint);

    void launch_project_forward(::cuda::stream_ref stream, std::uint32_t particle_count, device::CollisionBox collision_box, field::VectorView<const float> positions, field::VectorView<const float> corrections, std::uint32_t* collision_masks, field::VectorView<float> projected_positions);
    void launch_project_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, const std::uint32_t* collision_masks, field::VectorView<const float> position_tangent, field::VectorView<const float> correction_tangent, field::VectorView<float> projected_position_tangent);
    void launch_project_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, const std::uint32_t* collision_masks, field::VectorView<const double> projected_position_adjoint, field::VectorView<double> position_adjoint, field::VectorView<double> correction_adjoint);

    void launch_reconstruct_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float inverse_time_step, field::VectorView<const float> positions, field::VectorView<const float> corrected_positions, field::VectorView<float> velocities);
    void launch_reconstruct_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float inverse_time_step, field::VectorView<const float> position_tangent, field::VectorView<const float> corrected_position_tangent, field::VectorView<float> velocity_tangent);
    void launch_reconstruct_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float inverse_time_step, field::VectorView<const double> velocity_adjoint, field::VectorView<double> position_adjoint, field::VectorView<double> corrected_position_adjoint);

    void launch_vorticity_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> velocities, device::NeighborhoodView neighborhood, field::VectorView<float> vorticities);
    void launch_vorticity_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> velocities, field::VectorView<const float> position_tangent, field::VectorView<const float> velocity_tangent, device::NeighborhoodView neighborhood, field::VectorView<float> vorticity_tangent);
    void launch_vorticity_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> velocities, device::NeighborhoodView neighborhood, field::VectorView<const double> vorticity_adjoint, field::VectorView<double> position_adjoint, field::VectorView<double> velocity_adjoint);

    void launch_normal_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> vorticities, device::NeighborhoodView neighborhood, float* magnitudes, field::VectorView<float> normals, float* normalizers);
    void launch_normal_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> vorticities, field::VectorView<const float> position_tangent, field::VectorView<const float> vorticity_tangent, device::NeighborhoodView neighborhood, const float* magnitudes, field::VectorView<const float> normals, const float* normalizers, float* magnitude_tangent, field::VectorView<float> normal_tangent);
    void launch_normal_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> vorticities, device::NeighborhoodView neighborhood, const float* magnitudes, field::VectorView<const float> normals, const float* normalizers, field::VectorView<const double> normal_adjoint, field::VectorView<double> position_adjoint, field::VectorView<double> vorticity_adjoint);

    void launch_confinement_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, field::VectorView<const float> velocities, field::VectorView<const float> vorticities, field::VectorView<const float> normals, const float* confinement, field::VectorView<float> confined_velocities);
    void launch_confinement_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, field::VectorView<const float> vorticities, field::VectorView<const float> normals, const float* confinement, field::VectorView<const float> velocity_tangent, field::VectorView<const float> vorticity_tangent, field::VectorView<const float> normal_tangent, const float* confinement_tangent, field::VectorView<float> confined_velocity_tangent);
    void launch_confinement_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, field::VectorView<const float> vorticities, field::VectorView<const float> normals, const float* confinement, field::VectorView<const double> confined_velocity_adjoint, field::VectorView<double> velocity_adjoint, field::VectorView<double> vorticity_adjoint, field::VectorView<double> normal_adjoint, double* confinement_adjoint);

    void launch_xsph_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> velocities, device::NeighborhoodView neighborhood, const float* viscosity, field::VectorView<float> output_velocities);
    void launch_xsph_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> velocities, field::VectorView<const float> position_tangent, field::VectorView<const float> velocity_tangent, device::NeighborhoodView neighborhood, const float* viscosity, const float* viscosity_tangent, field::VectorView<float> output_velocity_tangent);
    void launch_xsph_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, field::VectorView<const float> topology_positions, field::VectorView<const float> positions, field::VectorView<const float> velocities, device::NeighborhoodView neighborhood, const float* viscosity, field::VectorView<const double> output_velocity_adjoint, field::VectorView<double> position_adjoint, field::VectorView<double> velocity_adjoint, double* viscosity_adjoint);

} // namespace physica::fluids::liquid::pbf::kernels

#endif
