# ============================================================================
# Particle Liquid Solvers
# ============================================================================
add_library(physica-fluids-liquid-particle)
target_sources(
        physica-fluids-liquid-particle
        PRIVATE
        domain/domain.cpp
        domain/domain.cu
        domain/device.h
        domain/device.cuh
        domain/interop.h
        domain/kernels.h
        neighborhood/neighborhood.cpp
        neighborhood/neighborhood.cu
        neighborhood/device.h
        neighborhood/device.cuh
        neighborhood/interop.h
        neighborhood/kernels.h
        density/density.cpp
        density/density.cu
        density/device.cuh
        density/kernels.h
        sph/sph.cpp
        sph/common.cu
        sph/wcsph.cu
        sph/wcsph.h
        sph/pcisph.cu
        sph/pcisph.h
        sph/iisph.cu
        sph/iisph.h
        sph/dfsph.cu
        sph/dfsph.h
        sph/kernels.h
        pbf/pbf.cpp
        pbf/pbf.cu
        pbf/kernels.h
        PUBLIC
        FILE_SET cxx_modules TYPE CXX_MODULES FILES
        particle.ixx
        domain/domain.ixx
        neighborhood/neighborhood.ixx
        density/density.ixx
        sph/sph.ixx
        pbf/pbf.ixx
)
target_include_directories(
        physica-fluids-liquid-particle
        PUBLIC
        "${PHYSICA_CLION_CUDA_INCLUDE_DIRECTORY}"
)
target_link_libraries(
        physica-fluids-liquid-particle
        PUBLIC
        CCCL::libcudacxx
        CUDA::toolkit
)
