#ifndef PHYSICA_FLUIDS_LIQUID_OPERATORS_SPH_DYNAMICS_KERNELS_H
#define PHYSICA_FLUIDS_LIQUID_OPERATORS_SPH_DYNAMICS_KERNELS_H

#include "../detail/cuda/types.h"

#include <cstdint>
#include <physica/cuda_stream.h>

namespace physica::fluids::liquid::cuda_detail::sph {
    void non_pressure_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float gravity_x, float gravity_y, float gravity_z, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> external_accelerations, ParticleParameterView parameters, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, VectorView<float> accelerations);
    void non_pressure_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> external_acceleration_tangent, ConstVectorView<float> position_tangent, ConstVectorView<float> velocity_tangent, ParticleParameterView parameters, ParticleParameterTangentView parameter_tangent, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, const float* density_tangent, VectorView<float> acceleration_tangent);
    void non_pressure_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ConstVectorView<float> velocities, ParticleParameterView parameters, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, ConstVectorView<double> acceleration_adjoint, VectorView<double> position_adjoint, VectorView<double> velocity_adjoint, VectorView<double> control_adjoint, double* density_adjoint, ParticleParameterAdjointView parameter_adjoint);

    void pressure_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ParticleParameterView parameters, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, const float* pressures, VectorView<float> accelerations);
    void pressure_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ConstVectorView<float> position_tangent, ParticleParameterView parameters, ParticleParameterTangentView parameter_tangent, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, const float* density_tangent, const float* pressures, const float* pressure_tangent, VectorView<float> acceleration_tangent);
    void pressure_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ParticleParameterView parameters, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, const float* pressures, ConstVectorView<double> acceleration_adjoint, VectorView<double> position_adjoint, double* density_adjoint, double* pressure_adjoint, ParticleParameterAdjointView parameter_adjoint);

    void integrate_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, Box domain, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> accelerations, VectorView<float> next_positions, VectorView<float> next_velocities);
    void integrate_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, Box domain, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> accelerations, ConstVectorView<float> position_tangent, ConstVectorView<float> velocity_tangent, ConstVectorView<float> acceleration_tangent, VectorView<float> next_position_tangent, VectorView<float> next_velocity_tangent);
    void integrate_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, Box domain, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> accelerations, ConstVectorView<double> next_position_adjoint, ConstVectorView<double> next_velocity_adjoint, VectorView<double> position_adjoint, VectorView<double> velocity_adjoint, VectorView<double> acceleration_adjoint);

    void predict_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, Box domain, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> non_pressure_accelerations, ConstVectorView<float> pressure_accelerations, VectorView<float> predicted_positions, VectorView<float> predicted_velocities);
    void predict_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, Box domain, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> non_pressure_accelerations, ConstVectorView<float> pressure_accelerations, ConstVectorView<float> position_tangent, ConstVectorView<float> velocity_tangent, ConstVectorView<float> non_pressure_acceleration_tangent, ConstVectorView<float> pressure_acceleration_tangent, VectorView<float> predicted_position_tangent, VectorView<float> predicted_velocity_tangent);
    void predict_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, Box domain, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> non_pressure_accelerations, ConstVectorView<float> pressure_accelerations, ConstVectorView<double> predicted_position_adjoint, ConstVectorView<double> predicted_velocity_adjoint, VectorView<double> position_adjoint, VectorView<double> velocity_adjoint, VectorView<double> non_pressure_acceleration_adjoint, VectorView<double> pressure_acceleration_adjoint);

    void add(::cuda::stream_ref stream, std::uint32_t particle_count, ConstVectorView<float> first, ConstVectorView<float> second, VectorView<float> output);
    void add_adjoint(::cuda::stream_ref stream, std::uint32_t particle_count, ConstVectorView<double> output_adjoint, VectorView<double> first_adjoint, VectorView<double> second_adjoint);
} // namespace physica::fluids::liquid::cuda_detail::sph

namespace physica::fluids::liquid::cuda_detail::wcsph {
    void launch_external_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float gravity_x, float gravity_y, float gravity_z, ConstVectorView<float> controls, VectorView<float> accelerations);

    void launch_eos_forward(::cuda::stream_ref stream, std::uint32_t particle_count, const float* densities, ParticleParameterView particles, const float* speed_of_sound, const float* tait_exponent, float* pressures);
    void launch_eos_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, const float* densities, const float* density_tangent, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, const float* speed_of_sound, const float* speed_of_sound_tangent, const float* tait_exponent, const float* tait_exponent_tangent, float* pressure_tangent);
    void launch_eos_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, const float* densities, ParticleParameterView particles, const float* speed_of_sound, const float* tait_exponent, const double* pressure_adjoint, double* density_adjoint, ParticleParameterAdjointView particle_adjoint, double* speed_of_sound_adjoint, double* tait_exponent_adjoint);

    void launch_artificial_viscosity_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ConstVectorView<float> velocities, ParticleParameterView particles, const float* speed_of_sound, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, VectorView<float> accelerations);
    void launch_artificial_viscosity_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> position_tangent, ConstVectorView<float> velocity_tangent, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, const float* speed_of_sound, const float* speed_of_sound_tangent, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, const float* density_tangent, VectorView<float> acceleration_tangent);
    void launch_artificial_viscosity_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> positions, ConstVectorView<float> velocities, ParticleParameterView particles, const float* speed_of_sound, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, ConstVectorView<double> acceleration_adjoint, VectorView<double> position_adjoint, VectorView<double> velocity_adjoint, double* density_adjoint, ParticleParameterAdjointView particle_adjoint, double* speed_of_sound_adjoint);

    void launch_surface_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float particle_radius, ConstVectorView<float> positions, ParticleParameterView particles, const float* boundary_surface_tension, NeighborhoodView neighborhood, BoundaryView boundary, VectorView<float> accelerations);
    void launch_surface_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float particle_radius, ConstVectorView<float> positions, ConstVectorView<float> position_tangent, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, const float* boundary_surface_tension, const float* boundary_surface_tension_tangent, NeighborhoodView neighborhood, BoundaryView boundary, VectorView<float> acceleration_tangent);
    void launch_surface_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float particle_radius, ConstVectorView<float> positions, ParticleParameterView particles, const float* boundary_surface_tension, NeighborhoodView neighborhood, BoundaryView boundary, ConstVectorView<double> acceleration_adjoint, VectorView<double> position_adjoint, ParticleParameterAdjointView particle_adjoint, double* boundary_surface_tension_adjoint);
} // namespace physica::fluids::liquid::cuda_detail::wcsph

namespace physica::fluids::liquid::cuda_detail::pcisph {
    void launch_pressure_update_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, const float* previous_pressures, const float* predicted_densities, const float* pressure_relaxation, float* pressures);
    void launch_pressure_update_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, const float* previous_pressures, const float* predicted_densities, const float* pressure_relaxation, const float* previous_pressure_tangent, const float* predicted_density_tangent, const float* pressure_relaxation_tangent, float* pressure_tangent);
    void launch_pressure_update_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, const float* previous_pressures, const float* predicted_densities, const float* pressure_relaxation, const double* pressure_adjoint, ParticleParameterAdjointView particle_adjoint, double* previous_pressure_adjoint, double* predicted_density_adjoint, double* pressure_relaxation_adjoint);
} // namespace physica::fluids::liquid::cuda_detail::pcisph

namespace physica::fluids::liquid::cuda_detail::iisph {
    void launch_jacobi_update_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, const float* densities, const float* previous_pressures, const float* predicted_densities, const float* jacobi_relaxation, float* pressures);
    void launch_jacobi_update_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, const float* densities, const float* density_tangent, const float* previous_pressures, const float* predicted_densities, const float* jacobi_relaxation, const float* previous_pressure_tangent, const float* predicted_density_tangent, const float* jacobi_relaxation_tangent, float* pressure_tangent);
    void launch_jacobi_update_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, const float* densities, const float* previous_pressures, const float* predicted_densities, const float* jacobi_relaxation, const double* pressure_adjoint, ParticleParameterAdjointView particle_adjoint, double* density_adjoint, double* previous_pressure_adjoint, double* predicted_density_adjoint, double* jacobi_relaxation_adjoint);
} // namespace physica::fluids::liquid::cuda_detail::iisph

namespace physica::fluids::liquid::cuda_detail::dfsph {
    void launch_projection_update_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, const float* densities, const float* target_densities, const float* previous_pressures, const float* predicted_densities, const float* projection_relaxation, float* pressures);
    void launch_projection_update_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, const float* densities, const float* density_tangent, const float* target_densities, const float* target_density_tangent, const float* previous_pressures, const float* predicted_densities, const float* projection_relaxation, const float* previous_pressure_tangent, const float* predicted_density_tangent, const float* projection_relaxation_tangent, float* pressure_tangent);
    void launch_projection_update_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, ParticleParameterView particles, const float* densities, const float* target_densities, const float* previous_pressures, const float* predicted_densities, const float* projection_relaxation, const double* pressure_adjoint, ParticleParameterAdjointView particle_adjoint, double* density_adjoint, double* target_density_adjoint, double* previous_pressure_adjoint, double* predicted_density_adjoint, double* projection_relaxation_adjoint);
} // namespace physica::fluids::liquid::cuda_detail::dfsph

#endif
