#ifndef PHYSICA_DEFORMABLES_CLOTH_SOLVERS_CHOI_KO_CHOI_KO_KERNELS_H
#define PHYSICA_DEFORMABLES_CLOTH_SOLVERS_CHOI_KO_CHOI_KO_KERNELS_H

#include <cstdint>
#include <physica/cuda_stream.h>
#include <simulation/field/device.cuh>

namespace physica::deformables::cloth::solvers::choi_ko::kernels {
    void assemble_triangles(::cuda::stream_ref stream, std::uint32_t triangle_count, float stretch_u_stiffness, float stretch_v_stiffness, float diagonal_u_stiffness, float diagonal_v_stiffness, float stretch_u_damping, float stretch_v_damping, float diagonal_u_damping, float diagonal_v_damping, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, simulation::VectorView<const float> direction_coefficients, const float* triangle_areas, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, float* triangle_conditions, simulation::VectorView<float> local_forces, float* local_symmetric_force_position_derivatives, float* local_force_velocity_derivatives);
    void assemble_hinges(::cuda::stream_ref stream, std::uint32_t hinge_count, std::uint32_t local_force_offset, std::uint32_t local_block_offset, float imperfection_stiffness, float bending_damping, const std::uint32_t* first_opposite, const std::uint32_t* second_opposite, const float* rest_spans, const float* area_sums, const float* stiffnesses, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, float* curvatures, float* curvature_first_derivatives, float* curvature_second_derivatives, float* responses, float* response_derivatives, simulation::VectorView<float> local_forces, float* local_symmetric_force_position_derivatives, float* local_force_velocity_derivatives);
    void gather(::cuda::stream_ref stream, std::uint32_t particle_count, std::uint32_t block_count, Vector3<float> gravity, const float* masses, simulation::VectorView<const float> external_forces, const std::uint32_t* force_contribution_offsets, const std::uint32_t* force_contribution_indices, simulation::VectorView<const float> local_forces, const std::uint32_t* block_contribution_offsets, const std::uint32_t* block_contribution_indices, const float* local_symmetric_force_position_derivatives, const float* local_force_velocity_derivatives, simulation::VectorView<float> forces, float* symmetric_force_position_derivatives, float* force_velocity_derivatives);
    void build_system_and_right_hand_side(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, const std::uint32_t* row_offsets, const std::uint32_t* column_indices, const float* masses, const float* symmetric_force_position_derivatives, const float* force_velocity_derivatives, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> previous_positions, simulation::VectorView<const float> previous_velocities, simulation::VectorView<const float> forces, float* system, simulation::VectorView<float> right_hand_side);
    void build_prescribed_displacement(::cuda::stream_ref stream, std::uint32_t particle_count, const std::uint32_t* fixed_vertex_mask, simulation::VectorView<const float> fixed_positions, simulation::VectorView<const float> positions, simulation::VectorView<float> prescribed_displacement);
    void subtract(::cuda::stream_ref stream, std::uint32_t particle_count, simulation::VectorView<const float> first, simulation::VectorView<const float> second, simulation::VectorView<float> result);
    void finalize(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, const std::uint32_t* fixed_vertex_mask, simulation::VectorView<const float> fixed_positions, simulation::VectorView<const float> positions, simulation::VectorView<const float> previous_positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> solution, simulation::VectorView<const float> prescribed_displacement, simulation::VectorView<float> bdf2_displacement, simulation::VectorView<float> next_positions, simulation::VectorView<float> next_velocities, simulation::VectorView<float> next_previous_positions, simulation::VectorView<float> next_previous_velocities);
} // namespace physica::deformables::cloth::solvers::choi_ko::kernels

#endif
