#ifndef PHYSICA_FLUIDS_LIQUID_PARTICLE_PBF_KERNELS_H
#define PHYSICA_FLUIDS_LIQUID_PARTICLE_PBF_KERNELS_H

#include "../domain/device.h"
#include "../neighborhood/device.h"
#include <physica/cuda_stream.h>

#include <cstdint>

namespace physica::fluids::liquid::particle::cuda_detail::pbf {

    void launch_predict_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float gravity_x, float gravity_y, float gravity_z, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> controls, VectorView<float> predicted_positions);
    void launch_predict_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, ConstVectorView<float> position_tangent, ConstVectorView<float> velocity_tangent, ConstVectorView<float> control_tangent, VectorView<float> predicted_position_tangent);
    void launch_predict_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, ConstVectorView<double> predicted_position_adjoint, VectorView<double> position_adjoint, VectorView<double> velocity_adjoint, VectorView<double> control_adjoint);

    void launch_lambda_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ParticleParameterView particles, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, const float* relaxation, VectorView<float> gradient_sums, float* denominators, float* lambdas);
    void launch_lambda_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> position_tangent, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, const float* density_tangent, const float* relaxation, const float* relaxation_tangent, VectorView<float> gradient_sum_tangent, float* denominator_tangent, float* lambda_tangent);
    void launch_lambda_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ParticleParameterView particles, NeighborhoodView neighborhood, BoundaryView boundary, const float* densities, ConstVectorView<float> gradient_sums, const float* denominators, const double* lambda_adjoint, VectorView<double> position_adjoint, double* density_adjoint, ParticleParameterAdjointView particle_adjoint, double* relaxation_adjoint);

    void launch_correction_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ParticleParameterView particles, NeighborhoodView neighborhood, BoundaryView boundary, const float* lambdas, const float* artificial_pressure_strength, const float* artificial_pressure_exponent, const float* artificial_pressure_radius, VectorView<float> corrections);
    void launch_correction_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> position_tangent, ParticleParameterView particles, ParticleParameterTangentView particle_tangent, NeighborhoodView neighborhood, BoundaryView boundary, const float* lambdas, const float* lambda_tangent, const float* artificial_pressure_strength, const float* artificial_pressure_strength_tangent, const float* artificial_pressure_exponent, const float* artificial_pressure_exponent_tangent, const float* artificial_pressure_radius, const float* artificial_pressure_radius_tangent, VectorView<float> correction_tangent);
    void launch_correction_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ParticleParameterView particles, NeighborhoodView neighborhood, BoundaryView boundary, const float* lambdas, const float* artificial_pressure_strength, const float* artificial_pressure_exponent, const float* artificial_pressure_radius, ConstVectorView<double> correction_adjoint, VectorView<double> position_adjoint, double* lambda_adjoint, ParticleParameterAdjointView particle_adjoint, double* artificial_pressure_strength_adjoint, double* artificial_pressure_exponent_adjoint, double* artificial_pressure_radius_adjoint);

    void launch_project_forward(::cuda::stream_ref stream, std::uint32_t particle_count, Box domain, ConstVectorView<float> positions, ConstVectorView<float> corrections, std::uint32_t* collision_masks, VectorView<float> projected_positions);
    void launch_project_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, const std::uint32_t* collision_masks, ConstVectorView<float> position_tangent, ConstVectorView<float> correction_tangent, VectorView<float> projected_position_tangent);
    void launch_project_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, const std::uint32_t* collision_masks, ConstVectorView<double> projected_position_adjoint, VectorView<double> position_adjoint, VectorView<double> correction_adjoint);

    void launch_reconstruct_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float inverse_time_step, ConstVectorView<float> positions, ConstVectorView<float> corrected_positions, VectorView<float> velocities);
    void launch_reconstruct_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float inverse_time_step, ConstVectorView<float> position_tangent, ConstVectorView<float> corrected_position_tangent, VectorView<float> velocity_tangent);
    void launch_reconstruct_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float inverse_time_step, ConstVectorView<double> velocity_adjoint, VectorView<double> position_adjoint, VectorView<double> corrected_position_adjoint);

    void launch_vorticity_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> velocities, NeighborhoodView neighborhood, VectorView<float> vorticities);
    void launch_vorticity_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> position_tangent, ConstVectorView<float> velocity_tangent, NeighborhoodView neighborhood, VectorView<float> vorticity_tangent);
    void launch_vorticity_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> velocities, NeighborhoodView neighborhood, ConstVectorView<double> vorticity_adjoint, VectorView<double> position_adjoint, VectorView<double> velocity_adjoint);

    void launch_normal_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> vorticities, NeighborhoodView neighborhood, float* magnitudes, VectorView<float> normals, float* normalizers);
    void launch_normal_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> vorticities, ConstVectorView<float> position_tangent, ConstVectorView<float> vorticity_tangent, NeighborhoodView neighborhood, const float* magnitudes, ConstVectorView<float> normals, const float* normalizers, float* magnitude_tangent, VectorView<float> normal_tangent);
    void launch_normal_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> vorticities, NeighborhoodView neighborhood, const float* magnitudes, ConstVectorView<float> normals, const float* normalizers, ConstVectorView<double> normal_adjoint, VectorView<double> position_adjoint, VectorView<double> vorticity_adjoint);

    void launch_confinement_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, ConstVectorView<float> velocities, ConstVectorView<float> vorticities, ConstVectorView<float> normals, const float* confinement, VectorView<float> confined_velocities);
    void launch_confinement_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, ConstVectorView<float> vorticities, ConstVectorView<float> normals, const float* confinement, ConstVectorView<float> velocity_tangent, ConstVectorView<float> vorticity_tangent, ConstVectorView<float> normal_tangent, const float* confinement_tangent, VectorView<float> confined_velocity_tangent);
    void launch_confinement_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, ConstVectorView<float> vorticities, ConstVectorView<float> normals, const float* confinement, ConstVectorView<double> confined_velocity_adjoint, VectorView<double> velocity_adjoint, VectorView<double> vorticity_adjoint, VectorView<double> normal_adjoint, double* confinement_adjoint);

    void launch_xsph_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> velocities, NeighborhoodView neighborhood, const float* viscosity, VectorView<float> output_velocities);
    void launch_xsph_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> velocities, ConstVectorView<float> position_tangent, ConstVectorView<float> velocity_tangent, NeighborhoodView neighborhood, const float* viscosity, const float* viscosity_tangent, VectorView<float> output_velocity_tangent);
    void launch_xsph_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, ConstVectorView<float> topology_positions, ConstVectorView<float> positions, ConstVectorView<float> velocities, NeighborhoodView neighborhood, const float* viscosity, ConstVectorView<double> output_velocity_adjoint, VectorView<double> position_adjoint, VectorView<double> velocity_adjoint, double* viscosity_adjoint);

} // namespace physica::fluids::liquid::particle::cuda_detail::pbf

#endif
