include_guard(GLOBAL)

add_library(cuDNN::cuDNN SHARED IMPORTED GLOBAL)
if (WIN32)
    set(PHYSICA_CUDNN_ROOT "C:/Program Files/NVIDIA/CUDNN/v9.24" CACHE PATH "Installed cuDNN SDK")
    find_path(PHYSICA_CUDNN_INCLUDE_DIRECTORY cudnn.h
            PATHS "${PHYSICA_CUDNN_ROOT}/include/13.3" NO_DEFAULT_PATH REQUIRED)
    find_library(PHYSICA_CUDNN_LIBRARY cudnn
            PATHS "${PHYSICA_CUDNN_ROOT}/lib/13.3/x64" NO_DEFAULT_PATH REQUIRED)
    find_file(PHYSICA_CUDNN_DLL cudnn64_9.dll
            PATHS "${PHYSICA_CUDNN_ROOT}/bin/13.3/x64" NO_DEFAULT_PATH REQUIRED)
    cmake_path(GET PHYSICA_CUDNN_DLL PARENT_PATH PHYSICA_CUDNN_DLL_DIRECTORY)
    file(GLOB PHYSICA_CUDNN_DLLS "${PHYSICA_CUDNN_DLL_DIRECTORY}/*.dll")
    set_target_properties(cuDNN::cuDNN PROPERTIES
            IMPORTED_IMPLIB "${PHYSICA_CUDNN_LIBRARY}"
            IMPORTED_LOCATION "${PHYSICA_CUDNN_DLL}")
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_path(PHYSICA_CUDNN_INCLUDE_DIRECTORY cudnn.h REQUIRED)
    find_library(PHYSICA_CUDNN_LIBRARY cudnn REQUIRED)
    set_target_properties(cuDNN::cuDNN PROPERTIES IMPORTED_LOCATION "${PHYSICA_CUDNN_LIBRARY}")
else ()
    message(FATAL_ERROR "cuDNN requires Windows or Linux")
endif ()

set_target_properties(cuDNN::cuDNN PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${PHYSICA_CUDNN_INCLUDE_DIRECTORY}")
