#ifndef PHYSICA_DEFORMABLES_CLOTH_SOLVERS_SURFACE_NEO_HOOKEAN_SURFACE_NEO_HOOKEAN_KERNELS_H
#define PHYSICA_DEFORMABLES_CLOTH_SOLVERS_SURFACE_NEO_HOOKEAN_SURFACE_NEO_HOOKEAN_KERNELS_H

#include <cstdint>
#include <physica/cuda_stream.h>
#include <simulation/field/device.cuh>

namespace physica::deformables::cloth::solvers::surface_neo_hookean::kernels {
    void evaluate_elements(::cuda::stream_ref stream, std::uint32_t triangle_count, float lame_lambda, float lame_mu, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, simulation::VectorView<const float> material_u_gradients, simulation::VectorView<const float> material_v_gradients, const float* triangle_weights, simulation::VectorView<const float> positions, simulation::VectorView<float> deformation_gradient_first_columns, simulation::VectorView<float> deformation_gradient_second_columns, float* surface_jacobians, float* log_surface_jacobians, float* triangle_energies, simulation::VectorView<float> triangle_gradients, float* triangle_hessians);
    void assemble_incremental_system(::cuda::stream_ref stream, std::uint32_t particle_count, float inverse_time_step_squared, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, const std::uint32_t* vertex_triangle_offsets, const std::uint32_t* vertex_triangles, const std::uint32_t* matrix_row_offsets, const std::uint32_t* matrix_column_indices, const std::uint32_t* block_contribution_offsets, const std::uint32_t* block_contributions, const float* masses, simulation::VectorView<const float> predicted_positions, simulation::VectorView<const float> positions, simulation::VectorView<const float> triangle_gradients, const float* triangle_hessians, simulation::VectorView<float> gradient, float* hessian);
    void compute_gershgorin_bounds(::cuda::stream_ref stream, std::uint32_t row_count, const std::uint32_t* row_offsets, const std::uint32_t* column_indices, const std::uint32_t* fixed_vertex_mask, const float* hessian, float* lower_bounds);
    void reduce_minimum(::cuda::stream_ref stream, std::uint32_t count, const float* values, double* result);
    void choose_regularization(::cuda::stream_ref stream, float positive_margin, const double* minimum_bound, float* shift);
    void build_regularized_hessian(::cuda::stream_ref stream, std::uint32_t row_count, const std::uint32_t* row_offsets, const std::uint32_t* column_indices, const std::uint32_t* fixed_vertex_mask, const float* shift, const float* hessian, float* regularized_hessian);
    void negate(::cuda::stream_ref stream, std::uint32_t particle_count, simulation::VectorView<const float> input, simulation::VectorView<float> output);
    void evaluate_directional_derivative(::cuda::stream_ref stream, std::uint32_t particle_count, const std::uint32_t* fixed_vertex_mask, simulation::VectorView<const float> gradient, simulation::VectorView<const float> direction, double* result);
    void evaluate_domain_steps(::cuda::stream_ref stream, std::uint32_t triangle_count, float domain_safety, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, simulation::VectorView<const float> material_u_gradients, simulation::VectorView<const float> material_v_gradients, simulation::VectorView<const float> positions, simulation::VectorView<const float> direction, float* triangle_domain_steps);
    void reduce_domain_step(::cuda::stream_ref stream, std::uint32_t triangle_count, const float* triangle_domain_steps, float* maximum_domain_step);
    void evaluate_potential(::cuda::stream_ref stream, std::uint32_t particle_count, std::uint32_t triangle_count, float inverse_time_step_squared, float lame_lambda, float lame_mu, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, simulation::VectorView<const float> material_u_gradients, simulation::VectorView<const float> material_v_gradients, const float* triangle_weights, const float* masses, simulation::VectorView<const float> predicted_positions, simulation::VectorView<const float> positions, double* potential);
    void evaluate_candidate_potentials(::cuda::stream_ref stream, std::uint32_t candidate_count, std::uint32_t particle_count, std::uint32_t triangle_count, float inverse_time_step_squared, float lame_lambda, float lame_mu, const float* candidate_contractions, const float* maximum_domain_step, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, simulation::VectorView<const float> material_u_gradients, simulation::VectorView<const float> material_v_gradients, const float* triangle_weights, const float* masses, simulation::VectorView<const float> predicted_positions, simulation::VectorView<const float> positions, simulation::VectorView<const float> direction, double* potentials);
    void select_step_size(::cuda::stream_ref stream, std::uint32_t candidate_count, float armijo_coefficient, const float* candidate_contractions, const float* maximum_domain_step, const double* current_potential, const double* directional_derivative, const double* candidate_potentials, float* accepted_step_size, std::uint32_t* accepted_candidate, double* accepted_potential);
    void update_positions(::cuda::stream_ref stream, std::uint32_t particle_count, const float* step_size, simulation::VectorView<const float> direction, simulation::VectorView<float> positions);
} // namespace physica::deformables::cloth::solvers::surface_neo_hookean::kernels

#endif

