#ifndef PHYSICA_FLUIDS_LIQUID_SOLVERS_SPH_DYNAMICS_KERNELS_H
#define PHYSICA_FLUIDS_LIQUID_SOLVERS_SPH_DYNAMICS_KERNELS_H

#include <fluids/liquid/device.cuh>
#include <cstdint>
#include <physica/cuda_stream.h>

namespace physica::fluids::liquid::solvers::sph::kernels::common {
    void non_pressure_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float gravity_x, float gravity_y, float gravity_z, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> external_accelerations, device::ParticleParameterView parameters, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, simulation::VectorView<float> accelerations);
    void non_pressure_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> external_acceleration_tangent, simulation::VectorView<const float> position_tangent, simulation::VectorView<const float> velocity_tangent, device::ParticleParameterView parameters, device::ParticleParameterTangentView parameter_tangent, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, const float* density_tangent, simulation::VectorView<float> acceleration_tangent);
    void non_pressure_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, device::ParticleParameterView parameters, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, simulation::VectorView<const double> acceleration_adjoint, simulation::VectorView<double> position_adjoint, simulation::VectorView<double> velocity_adjoint, simulation::VectorView<double> control_adjoint, double* density_adjoint, device::ParticleParameterAdjointView parameter_adjoint);

    void pressure_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, device::ParticleParameterView parameters, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, const float* pressures, simulation::VectorView<float> accelerations);
    void pressure_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, simulation::VectorView<const float> position_tangent, device::ParticleParameterView parameters, device::ParticleParameterTangentView parameter_tangent, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, const float* density_tangent, const float* pressures, const float* pressure_tangent, simulation::VectorView<float> acceleration_tangent);
    void pressure_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, device::ParticleParameterView parameters, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, const float* pressures, simulation::VectorView<const double> acceleration_adjoint, simulation::VectorView<double> position_adjoint, double* density_adjoint, double* pressure_adjoint, device::ParticleParameterAdjointView parameter_adjoint);

    void integrate_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, device::CollisionBox collision_box, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> accelerations, simulation::VectorView<float> next_positions, simulation::VectorView<float> next_velocities);
    void integrate_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, device::CollisionBox collision_box, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> accelerations, simulation::VectorView<const float> position_tangent, simulation::VectorView<const float> velocity_tangent, simulation::VectorView<const float> acceleration_tangent, simulation::VectorView<float> next_position_tangent, simulation::VectorView<float> next_velocity_tangent);
    void integrate_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, device::CollisionBox collision_box, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> accelerations, simulation::VectorView<const double> next_position_adjoint, simulation::VectorView<const double> next_velocity_adjoint, simulation::VectorView<double> position_adjoint, simulation::VectorView<double> velocity_adjoint, simulation::VectorView<double> acceleration_adjoint);

    void predict_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, device::CollisionBox collision_box, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> non_pressure_accelerations, simulation::VectorView<const float> pressure_accelerations, simulation::VectorView<float> predicted_positions, simulation::VectorView<float> predicted_velocities);
    void predict_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, device::CollisionBox collision_box, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> non_pressure_accelerations, simulation::VectorView<const float> pressure_accelerations, simulation::VectorView<const float> position_tangent, simulation::VectorView<const float> velocity_tangent, simulation::VectorView<const float> non_pressure_acceleration_tangent, simulation::VectorView<const float> pressure_acceleration_tangent, simulation::VectorView<float> predicted_position_tangent, simulation::VectorView<float> predicted_velocity_tangent);
    void predict_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, device::CollisionBox collision_box, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> non_pressure_accelerations, simulation::VectorView<const float> pressure_accelerations, simulation::VectorView<const double> predicted_position_adjoint, simulation::VectorView<const double> predicted_velocity_adjoint, simulation::VectorView<double> position_adjoint, simulation::VectorView<double> velocity_adjoint, simulation::VectorView<double> non_pressure_acceleration_adjoint, simulation::VectorView<double> pressure_acceleration_adjoint);

    void add(::cuda::stream_ref stream, std::uint32_t particle_count, simulation::VectorView<const float> first, simulation::VectorView<const float> second, simulation::VectorView<float> output);
    void add_adjoint(::cuda::stream_ref stream, std::uint32_t particle_count, simulation::VectorView<const double> output_adjoint, simulation::VectorView<double> first_adjoint, simulation::VectorView<double> second_adjoint);
} // namespace physica::fluids::liquid::solvers::sph::kernels::common

namespace physica::fluids::liquid::solvers::sph::kernels::wcsph {
    void launch_external_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float gravity_x, float gravity_y, float gravity_z, simulation::VectorView<const float> controls, simulation::VectorView<float> accelerations);

    void launch_eos_forward(::cuda::stream_ref stream, std::uint32_t particle_count, const float* densities, device::ParticleParameterView particles, const float* speed_of_sound, const float* tait_exponent, float* pressures);
    void launch_eos_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, const float* densities, const float* density_tangent, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, const float* speed_of_sound, const float* speed_of_sound_tangent, const float* tait_exponent, const float* tait_exponent_tangent, float* pressure_tangent);
    void launch_eos_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, const float* densities, device::ParticleParameterView particles, const float* speed_of_sound, const float* tait_exponent, const double* pressure_adjoint, double* density_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* speed_of_sound_adjoint, double* tait_exponent_adjoint);

    void launch_artificial_viscosity_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, device::ParticleParameterView particles, const float* speed_of_sound, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, simulation::VectorView<float> accelerations);
    void launch_artificial_viscosity_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> position_tangent, simulation::VectorView<const float> velocity_tangent, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, const float* speed_of_sound, const float* speed_of_sound_tangent, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, const float* density_tangent, simulation::VectorView<float> acceleration_tangent);
    void launch_artificial_viscosity_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, device::ParticleParameterView particles, const float* speed_of_sound, device::NeighborhoodView neighborhood, device::BoundaryView boundary, const float* densities, simulation::VectorView<const double> acceleration_adjoint, simulation::VectorView<double> position_adjoint, simulation::VectorView<double> velocity_adjoint, double* density_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* speed_of_sound_adjoint);

    void launch_surface_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float particle_radius, simulation::VectorView<const float> positions, device::ParticleParameterView particles, const float* boundary_surface_tension, device::NeighborhoodView neighborhood, device::BoundaryView boundary, simulation::VectorView<float> accelerations);
    void launch_surface_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float particle_radius, simulation::VectorView<const float> positions, simulation::VectorView<const float> position_tangent, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, const float* boundary_surface_tension, const float* boundary_surface_tension_tangent, device::NeighborhoodView neighborhood, device::BoundaryView boundary, simulation::VectorView<float> acceleration_tangent);
    void launch_surface_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float support_radius, float particle_radius, simulation::VectorView<const float> positions, device::ParticleParameterView particles, const float* boundary_surface_tension, device::NeighborhoodView neighborhood, device::BoundaryView boundary, simulation::VectorView<const double> acceleration_adjoint, simulation::VectorView<double> position_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* boundary_surface_tension_adjoint);
} // namespace physica::fluids::liquid::solvers::sph::kernels::wcsph

namespace physica::fluids::liquid::solvers::sph::kernels::pcisph {
    void launch_pressure_update_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, const float* previous_pressures, const float* predicted_densities, const float* pressure_relaxation, float* pressures);
    void launch_pressure_update_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, const float* previous_pressures, const float* predicted_densities, const float* pressure_relaxation, const float* previous_pressure_tangent, const float* predicted_density_tangent, const float* pressure_relaxation_tangent, float* pressure_tangent);
    void launch_pressure_update_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, const float* previous_pressures, const float* predicted_densities, const float* pressure_relaxation, const double* pressure_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* previous_pressure_adjoint, double* predicted_density_adjoint, double* pressure_relaxation_adjoint);
} // namespace physica::fluids::liquid::solvers::sph::kernels::pcisph

namespace physica::fluids::liquid::solvers::sph::kernels::iisph {
    void launch_jacobi_update_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, const float* densities, const float* previous_pressures, const float* predicted_densities, const float* jacobi_relaxation, float* pressures);
    void launch_jacobi_update_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, const float* densities, const float* density_tangent, const float* previous_pressures, const float* predicted_densities, const float* jacobi_relaxation, const float* previous_pressure_tangent, const float* predicted_density_tangent, const float* jacobi_relaxation_tangent, float* pressure_tangent);
    void launch_jacobi_update_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, const float* densities, const float* previous_pressures, const float* predicted_densities, const float* jacobi_relaxation, const double* pressure_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* density_adjoint, double* previous_pressure_adjoint, double* predicted_density_adjoint, double* jacobi_relaxation_adjoint);
} // namespace physica::fluids::liquid::solvers::sph::kernels::iisph

namespace physica::fluids::liquid::solvers::sph::kernels::dfsph {
    void launch_projection_update_forward(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, const float* densities, const float* target_densities, const float* previous_pressures, const float* predicted_densities, const float* projection_relaxation, float* pressures);
    void launch_projection_update_jvp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, device::ParticleParameterTangentView particle_tangent, const float* densities, const float* density_tangent, const float* target_densities, const float* target_density_tangent, const float* previous_pressures, const float* predicted_densities, const float* projection_relaxation, const float* previous_pressure_tangent, const float* predicted_density_tangent, const float* projection_relaxation_tangent, float* pressure_tangent);
    void launch_projection_update_vjp(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, float reference_gradient_norm, device::ParticleParameterView particles, const float* densities, const float* target_densities, const float* previous_pressures, const float* predicted_densities, const float* projection_relaxation, const double* pressure_adjoint, device::ParticleParameterAdjointView particle_adjoint, double* density_adjoint, double* target_density_adjoint, double* previous_pressure_adjoint, double* predicted_density_adjoint, double* projection_relaxation_adjoint);
} // namespace physica::fluids::liquid::solvers::sph::kernels::dfsph

#endif
