#ifndef PHYSICA_DEFORMABLES_CLOTH_SOLVERS_DISCRETE_SHELLS_DISCRETE_SHELLS_KERNELS_H
#define PHYSICA_DEFORMABLES_CLOTH_SOLVERS_DISCRETE_SHELLS_DISCRETE_SHELLS_KERNELS_H

#include <cstdint>
#include <physica/cuda_stream.h>
#include <simulation/field/device.cuh>

namespace physica::deformables::cloth::solvers::discrete_shells::kernels {
    void prepare_newmark(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, const std::uint32_t* fixed_vertex_mask, simulation::VectorView<const float> fixed_positions, simulation::VectorView<const float> positions, simulation::VectorView<const float> velocities, simulation::VectorView<const float> accelerations, simulation::VectorView<float> position_predictor, simulation::VectorView<float> velocity_predictor, simulation::VectorView<float> candidate_positions);
    void evaluate_hinge_angles(::cuda::stream_ref stream, std::uint32_t hinge_count, const std::uint32_t* edge_first, const std::uint32_t* edge_second, const std::uint32_t* first_opposite, const std::uint32_t* second_opposite, simulation::VectorView<const float> positions, float* angles);
    void evaluate_edges(::cuda::stream_ref stream, std::uint32_t edge_count, float length_stiffness, const std::uint32_t* edge_first, const std::uint32_t* edge_second, const float* rest_lengths, simulation::VectorView<const float> positions, float* conditions, float* energies, simulation::VectorView<float> gradients, float* hessians);
    void evaluate_triangles(::cuda::stream_ref stream, std::uint32_t triangle_count, float area_stiffness, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, const float* rest_areas, simulation::VectorView<const float> positions, float* conditions, float* energies, simulation::VectorView<float> gradients, float* hessians);
    void evaluate_hinges(::cuda::stream_ref stream, std::uint32_t hinge_count, float time_step, float bending_stiffness, float bending_damping, const std::uint32_t* edge_first, const std::uint32_t* edge_second, const std::uint32_t* first_opposite, const std::uint32_t* second_opposite, const float* rest_angles, const float* previous_angles, const float* weights, simulation::VectorView<const float> positions, float* angles, float* angle_deltas, float* angle_rates, float* energies, float* damping_potentials, simulation::VectorView<float> angle_gradients, float* angle_hessians, simulation::VectorView<float> energy_gradients, float* energy_hessians, simulation::VectorView<float> damping_residuals, float* damping_jacobians);
    void assemble_system(::cuda::stream_ref stream, std::uint32_t particle_count, std::uint32_t edge_count, std::uint32_t triangle_count, float mass_coefficient, Vector3<float> gravity, const std::uint32_t* edge_first, const std::uint32_t* edge_second, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, const std::uint32_t* hinge_edge_first, const std::uint32_t* hinge_edge_second, const std::uint32_t* hinge_first_opposite, const std::uint32_t* hinge_second_opposite, const std::uint32_t* vertex_edge_offsets, const std::uint32_t* vertex_edges, const std::uint32_t* vertex_triangle_offsets, const std::uint32_t* vertex_triangles, const std::uint32_t* vertex_hinge_offsets, const std::uint32_t* vertex_hinges, const std::uint32_t* matrix_row_offsets, const std::uint32_t* matrix_column_indices, const std::uint32_t* energy_contribution_offsets, const std::uint32_t* energy_contributions, const std::uint32_t* damping_contribution_offsets, const std::uint32_t* damping_contributions, const float* masses, simulation::VectorView<const float> external_forces, simulation::VectorView<const float> position_predictor, simulation::VectorView<const float> positions, simulation::VectorView<const float> edge_gradients, const float* edge_hessians, simulation::VectorView<const float> triangle_gradients, const float* triangle_hessians, simulation::VectorView<const float> hinge_gradients, const float* hinge_hessians, simulation::VectorView<const float> damping_residuals, const float* damping_jacobians, simulation::VectorView<float> energy_gradient, simulation::VectorView<float> damping_residual, simulation::VectorView<float> residual, float* energy_hessian, float* damping_jacobian, float* unregularized_system);
    void compute_gershgorin_bounds(::cuda::stream_ref stream, std::uint32_t row_count, const std::uint32_t* row_offsets, const std::uint32_t* column_indices, const std::uint32_t* fixed_vertex_mask, const float* matrix, float* lower_bounds);
    void reduce_minimum(::cuda::stream_ref stream, std::uint32_t count, const float* values, double* result);
    void choose_regularization(::cuda::stream_ref stream, float positive_margin, const double* minimum_bound, float* shift);
    void build_regularized_system(::cuda::stream_ref stream, std::uint32_t row_count, const std::uint32_t* row_offsets, const std::uint32_t* column_indices, const std::uint32_t* fixed_vertex_mask, const float* shift, const float* unregularized_system, float* system);
    void negate(::cuda::stream_ref stream, std::uint32_t particle_count, simulation::VectorView<const float> input, simulation::VectorView<float> output);
    void evaluate_directional_derivative(::cuda::stream_ref stream, std::uint32_t particle_count, const std::uint32_t* fixed_vertex_mask, simulation::VectorView<const float> gradient, simulation::VectorView<const float> direction, double* result);
    void evaluate_potential(::cuda::stream_ref stream, std::uint32_t particle_count, std::uint32_t edge_count, std::uint32_t triangle_count, std::uint32_t hinge_count, float time_step, float length_stiffness, float area_stiffness, float bending_stiffness, float bending_damping, Vector3<float> gravity, const std::uint32_t* edge_first, const std::uint32_t* edge_second, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, const std::uint32_t* hinge_edge_first, const std::uint32_t* hinge_edge_second, const std::uint32_t* hinge_first_opposite, const std::uint32_t* hinge_second_opposite, const float* edge_rest_lengths, const float* triangle_rest_areas, const float* hinge_rest_angles, const float* previous_hinge_angles, const float* hinge_weights, const float* masses, simulation::VectorView<const float> external_forces, simulation::VectorView<const float> position_predictor, simulation::VectorView<const float> positions, double* potential);
    void evaluate_candidate_potentials(::cuda::stream_ref stream, std::uint32_t candidate_count, std::uint32_t particle_count, std::uint32_t edge_count, std::uint32_t triangle_count, std::uint32_t hinge_count, float time_step, float length_stiffness, float area_stiffness, float bending_stiffness, float bending_damping, Vector3<float> gravity, const float* candidate_steps, const std::uint32_t* edge_first, const std::uint32_t* edge_second, const std::uint32_t* triangle_first, const std::uint32_t* triangle_second, const std::uint32_t* triangle_third, const std::uint32_t* hinge_edge_first, const std::uint32_t* hinge_edge_second, const std::uint32_t* hinge_first_opposite, const std::uint32_t* hinge_second_opposite, const float* edge_rest_lengths, const float* triangle_rest_areas, const float* hinge_rest_angles, const float* previous_hinge_angles, const float* hinge_weights, const float* masses, simulation::VectorView<const float> external_forces, simulation::VectorView<const float> position_predictor, simulation::VectorView<const float> positions, simulation::VectorView<const float> direction, double* potentials);
    void select_step_size(::cuda::stream_ref stream, std::uint32_t candidate_count, float armijo_coefficient, const float* candidate_steps, const double* current_potential, const double* directional_derivative, const double* candidate_potentials, float* accepted_step_size, std::uint32_t* accepted_candidate, double* accepted_potential);
    void update_positions(::cuda::stream_ref stream, std::uint32_t particle_count, const float* step_size, simulation::VectorView<const float> direction, simulation::VectorView<float> positions);
    void reconstruct_newmark(::cuda::stream_ref stream, std::uint32_t particle_count, float time_step, simulation::VectorView<const float> position_predictor, simulation::VectorView<const float> velocity_predictor, simulation::VectorView<const float> positions, simulation::VectorView<float> velocities, simulation::VectorView<float> accelerations);
} // namespace physica::deformables::cloth::solvers::discrete_shells::kernels

#endif
